// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa-wjvO22euVvm6hoAljRHN6R_CL_SjHg',
    appId: '1:967586967731:web:b069d5d54c3d69594700c6',
    messagingSenderId: '967586967731',
    projectId: 'referralfreindapp',
    authDomain: 'referralfreindapp.firebaseapp.com',
    storageBucket: 'referralfreindapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVZIKh0ptctLny9jYBtP-83MDYta5JlkQ',
    appId: '1:967586967731:android:348d03a66743b5e84700c6',
    messagingSenderId: '967586967731',
    projectId: 'referralfreindapp',
    storageBucket: 'referralfreindapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDACKMr7qwYFkIzDSJr195PVMaaUMd8BsY',
    appId: '1:967586967731:ios:8e56ee9321d8d67a4700c6',
    messagingSenderId: '967586967731',
    projectId: 'referralfreindapp',
    storageBucket: 'referralfreindapp.appspot.com',
    iosBundleId: 'com.example.referralFreindsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDACKMr7qwYFkIzDSJr195PVMaaUMd8BsY',
    appId: '1:967586967731:ios:9eecdbac017b3d984700c6',
    messagingSenderId: '967586967731',
    projectId: 'referralfreindapp',
    storageBucket: 'referralfreindapp.appspot.com',
    iosBundleId: 'com.example.referralFreindsapp.RunnerTests',
  );
}
